# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

# Site settings
title: "Mit dem Wissen wächst der Zweifel."
description: > # this means to ignore newlines until "email:"
   A personal website and blog by Tobias Doll

email: mail@tobiasdoll.de
#blog logo
logo: "/assets/images/td_logo.png"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Tobias Doll'
author: 'Tobias Doll'
author_image: "/assets/images/author_2.jpg"

paginate:	5

url: "http://tobysoby.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/tobysoby
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://www.facebook.com/te.de.7798
    desc: Connect with me on facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon: github
    url:  https://github.com/tobysoby
    desc: Fork me on github
    share_url:
    share_title:
    share_link:

  - icon: xing
    url:  https://www.xing.com/profile/Tobias_Doll5?sc_o=mxb_p
    desc: Connect with me on xing
    share_url:
    share_title:
    share_link:

  - icon: linkedin
    url:  https://www.linkedin.com/profile/view?id=376725901
    desc: Connect with me on linkedin
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

